POST http://localhost:8090/users 
content-type: application/json

{
    "username": "",
    "password": "1234",
    "email": "julio123@gmail.com",
    "names": "davee",
    "date": "",
    "about": "fULL FUTBOL xd",
    "city": "Guayaquil"
}