POST http://localhost:8080/pets 
content-type: application/json

{
    "user": "6171be69b59eaf42bf8520d3",
    "name": "Negro",
    "dateBorn": "2018-01-21T18:20:56.304Z",
    "city": "Pajan",
    "description": "Es negrito, es dulce, bonita",
    "adoption": "true"
}