POST http://localhost:8090/login 
content-type: application/json
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1YXNlbmVndWVyIiwicHJvZmlsZSI6IjYxOTgwN2I2ZGY0ZDc2OTlkZDkzMDVlMyIsImlhdCI6MTYzNzM1MzQ1M30.POikIX2C5kExAuFPqZDjnKKnyXytawVnKZr_L1b4uBA

{
    "username": "suaseneguer",
    "password": "1234"
}